/* Generated by migration/generate-rules.ts from the Mongoose schemas. Do not edit by hand. */
import type { Rule } from './rules';

export const RULES: Record<string, Record<string, Rule>> = {
  "user": {
    "name": {
      "type": "String",
      "required": "User name is required",
      "trim": true
    },
    "email": {
      "type": "String",
      "required": "Email address is required",
      "trim": true,
      "lowercase": true
    },
    "password": {
      "type": "String",
      "required": "Password is required"
    },
    "role": {
      "type": "String",
      "required": "User role is required",
      "default": {
        "value": "Receptionist"
      },
      "enum": {
        "values": [
          "Admin",
          "Pathologist",
          "Lab Technician",
          "Receptionist",
          "Accountant",
          "Phlebotomist"
        ]
      }
    },
    "mobile": {
      "type": "String",
      "required": "Mobile number is required",
      "trim": true
    },
    "status": {
      "type": "String",
      "default": {
        "value": "Active"
      },
      "enum": {
        "values": [
          "Active",
          "Inactive"
        ]
      }
    },
    "refreshToken": {
      "type": "String"
    },
    "permissions": {
      "type": "Array",
      "item": "String"
    },
    "sessionsValidFrom": {
      "type": "Date"
    }
  },
  "rolePermission": {
    "role": {
      "type": "String",
      "required": true
    },
    "permissions": {
      "type": "Array",
      "default": {
        "value": []
      },
      "item": "String"
    },
    "updatedBy.userId": {
      "type": "String"
    },
    "updatedBy.name": {
      "type": "String"
    },
    "updatedBy.at": {
      "type": "Date"
    }
  },
  "auditLog": {
    "action": {
      "type": "String",
      "required": true
    },
    "module": {
      "type": "String",
      "required": true
    },
    "performedBy": {
      "type": "Mixed",
      "required": true
    },
    "performedByName": {
      "type": "String"
    },
    "userRole": {
      "type": "String"
    },
    "ipAddress": {
      "type": "String"
    },
    "targetId": {
      "type": "String"
    },
    "details": {
      "type": "Mixed"
    }
  },
  "department": {
    "departmentName": {
      "type": "String",
      "required": "Department name is required",
      "trim": true
    },
    "departmentCode": {
      "type": "String",
      "required": "Department code is required",
      "trim": true,
      "uppercase": true
    },
    "description": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "status": {
      "type": "String",
      "required": "Status is required",
      "default": {
        "value": "Active"
      },
      "enum": {
        "values": [
          "Active",
          "Inactive"
        ]
      }
    }
  },
  "doctor": {
    "doctorName": {
      "type": "String",
      "required": "Doctor name is required",
      "trim": true
    },
    "department": {
      "type": "ObjectId",
      "required": "Department is required"
    },
    "gender": {
      "type": "String",
      "default": {
        "value": "Male"
      },
      "enum": {
        "values": [
          "Male",
          "Female",
          "Other"
        ]
      }
    },
    "degree": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "specialty": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "mobile": {
      "type": "String",
      "required": "Mobile number is required",
      "trim": true
    },
    "email": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true,
      "lowercase": true
    },
    "dob": {
      "type": "Date"
    },
    "area": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "areaCode": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "hospital": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "paymentTerm": {
      "type": "String",
      "default": {
        "value": "Monthly"
      },
      "enum": {
        "values": [
          "Daily",
          "Weekly",
          "Monthly",
          "Immediate"
        ]
      }
    },
    "discountType": {
      "type": "String",
      "default": {
        "value": "Percentage"
      },
      "enum": {
        "values": [
          "Percentage",
          "Fixed",
          "No Discount Only Cut"
        ]
      }
    },
    "discountPercentage": {
      "type": "Number",
      "default": {
        "value": 0
      },
      "min": [
        0
      ],
      "max": [
        100
      ]
    },
    "commission": {
      "type": "Number",
      "default": {
        "value": 0
      },
      "min": [
        0
      ],
      "max": [
        100
      ]
    },
    "addedBy": {
      "type": "ObjectId"
    },
    "status": {
      "type": "String",
      "required": "Status is required",
      "default": {
        "value": "Active"
      },
      "enum": {
        "values": [
          "Active",
          "Inactive"
        ]
      }
    }
  },
  "organization": {
    "organizationName": {
      "type": "String",
      "required": "Organization name is required",
      "trim": true
    },
    "contactPerson": {
      "type": "String",
      "required": "Contact person is required",
      "trim": true
    },
    "mobile": {
      "type": "String",
      "required": "Mobile number is required",
      "trim": true
    },
    "email": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true,
      "lowercase": true
    },
    "address": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "city": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "state": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "gstNumber": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "contractRate": {
      "type": "String",
      "default": {
        "value": "Corporate"
      },
      "enum": {
        "values": [
          "Corporate",
          "Standard",
          "Discounted"
        ]
      }
    },
    "discount": {
      "type": "Number",
      "default": {
        "value": 0
      },
      "min": [
        0
      ],
      "max": [
        100
      ]
    },
    "creditLimit": {
      "type": "Number",
      "default": {
        "value": 0
      },
      "min": [
        0
      ]
    },
    "paymentTerms": {
      "type": "String",
      "default": {
        "value": "Net 30"
      },
      "enum": {
        "values": [
          "Net 15",
          "Net 30",
          "Net 45",
          "Net 60",
          "Immediate"
        ]
      }
    },
    "status": {
      "type": "String",
      "required": "Status is required",
      "default": {
        "value": "Active"
      },
      "enum": {
        "values": [
          "Active",
          "Inactive"
        ]
      }
    }
  },
  "labTest": {
    "testName": {
      "type": "String",
      "required": "Test name is required",
      "trim": true
    },
    "testCode": {
      "type": "String",
      "required": "Test code is required",
      "trim": true,
      "uppercase": true
    },
    "department": {
      "type": "ObjectId",
      "required": "Department is required"
    },
    "testType": {
      "type": "String",
      "default": {
        "value": "Routine"
      },
      "enum": {
        "values": [
          "Routine",
          "Special",
          "Urgent",
          "Profile"
        ]
      }
    },
    "sampleType": {
      "type": "String",
      "default": {
        "value": "Whole Blood"
      },
      "trim": true
    },
    "sampleContainer": {
      "type": "String",
      "default": {
        "value": "EDTA Vial"
      },
      "trim": true
    },
    "rate": {
      "type": "Number",
      "required": true,
      "min": [
        0
      ]
    },
    "patientRate": {
      "type": "Number",
      "required": true,
      "min": [
        0
      ]
    },
    "corporateRate": {
      "type": "Number",
      "required": true,
      "min": [
        0
      ]
    },
    "doctorRate": {
      "type": "Number",
      "required": true,
      "min": [
        0
      ]
    },
    "emergencyRate": {
      "type": "Number",
      "required": true,
      "min": [
        0
      ]
    },
    "referralRate": {
      "type": "Number",
      "default": {
        "value": 0
      },
      "min": [
        0
      ]
    },
    "processingMode": {
      "type": "String",
      "default": {
        "value": "In-house"
      },
      "enum": {
        "values": [
          "In-house",
          "Outsource"
        ]
      }
    },
    "outsourceLab": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "outsourceCost": {
      "type": "Number",
      "default": {
        "value": 0
      },
      "min": [
        0
      ]
    },
    "tpa": {
      "type": "ObjectId",
      "default": {
        "value": null
      }
    },
    "discountAllowed": {
      "type": "Boolean",
      "default": {
        "value": true
      }
    },
    "fastingRequired": {
      "type": "Boolean",
      "default": {
        "value": false
      }
    },
    "preparationRequired": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "turnaroundTime": {
      "type": "String",
      "default": {
        "value": "24 Hours"
      },
      "trim": true
    },
    "interpretationTitle": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "interpretation": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "reportTemplate": {
      "type": "Embedded",
      "default": {
        "value": null
      },
      "sub": {
        "attachment": {
          "type": "ObjectId",
          "required": true
        },
        "fileName": {
          "type": "String",
          "required": true
        },
        "size": {
          "type": "Number",
          "default": {
            "value": 0
          }
        },
        "uploadedAt": {
          "type": "Date",
          "default": {
            "now": true
          }
        },
        "uploadedBy": {
          "type": "String",
          "default": {
            "value": ""
          }
        }
      }
    },
    "parameters": {
      "type": "Array",
      "of": {
        "parameterName": {
          "type": "String",
          "required": true,
          "trim": true
        },
        "shortName": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "unit": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "maleReferenceRange": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "femaleReferenceRange": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "childReferenceRange": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "criticalLow": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "criticalHigh": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "method": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "resultType": {
          "type": "String",
          "default": {
            "value": "Numeric"
          },
          "enum": {
            "values": [
              "Numeric",
              "Text",
              "Dropdown",
              "Positive/Negative",
              "Reactive/Non-Reactive",
              "Normal/Abnormal",
              "Header"
            ]
          }
        },
        "displayOrder": {
          "type": "Number",
          "default": {
            "value": 1
          }
        },
        "paraFor": {
          "type": "String",
          "default": {
            "value": "ALL"
          },
          "enum": {
            "values": [
              "ALL",
              "MALE",
              "FEMALE"
            ]
          }
        },
        "minValue": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "maxValue": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "highRange": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "lowRange": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "ageFromDays": {
          "type": "Number",
          "default": {
            "value": 0
          },
          "min": [
            0
          ]
        },
        "ageToDays": {
          "type": "Number",
          "default": {
            "value": 0
          },
          "min": [
            0
          ]
        },
        "referenceText": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "formula": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        }
      }
    },
    "status": {
      "type": "String",
      "required": "Status is required",
      "default": {
        "value": "Active"
      },
      "enum": {
        "values": [
          "Active",
          "Inactive"
        ]
      }
    }
  },
  "testAttachment": {
    "test": {
      "type": "ObjectId",
      "required": true
    },
    "fileName": {
      "type": "String",
      "required": true,
      "trim": true
    },
    "mimeType": {
      "type": "String",
      "required": true
    },
    "size": {
      "type": "Number",
      "required": true
    },
    "data": {
      "type": "Buffer",
      "required": true
    },
    "kind": {
      "type": "String",
      "default": {
        "value": "reference"
      },
      "enum": {
        "values": [
          "reference",
          "report-template"
        ]
      }
    },
    "uploadedBy.userId": {
      "type": "ObjectId"
    },
    "uploadedBy.name": {
      "type": "String"
    }
  },
  "testPackage": {
    "packageName": {
      "type": "String",
      "required": "Package name is required",
      "trim": true
    },
    "packageCode": {
      "type": "String",
      "required": "Package code is required",
      "trim": true,
      "uppercase": true
    },
    "description": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "department": {
      "type": "ObjectId"
    },
    "tests": {
      "type": "Array",
      "item": "ObjectId"
    },
    "rate": {
      "type": "Number",
      "required": "Package rate is required",
      "min": [
        0
      ]
    },
    "referralRate": {
      "type": "Number",
      "default": {
        "value": 0
      },
      "min": [
        0
      ]
    },
    "discountAllowed": {
      "type": "Boolean",
      "default": {
        "value": true
      }
    },
    "status": {
      "type": "String",
      "required": "Status is required",
      "default": {
        "value": "Active"
      },
      "enum": {
        "values": [
          "Active",
          "Inactive"
        ]
      }
    }
  },
  "rateHistory": {
    "test": {
      "type": "ObjectId",
      "required": true
    },
    "testCode": {
      "type": "String",
      "required": true
    },
    "testName": {
      "type": "String",
      "required": true
    },
    "previousRates.rate": {
      "type": "Number",
      "required": true
    },
    "previousRates.patientRate": {
      "type": "Number",
      "required": true
    },
    "previousRates.corporateRate": {
      "type": "Number",
      "required": true
    },
    "previousRates.doctorRate": {
      "type": "Number",
      "required": true
    },
    "previousRates.emergencyRate": {
      "type": "Number",
      "required": true
    },
    "previousRates.referralRate": {
      "type": "Number"
    },
    "newRates.rate": {
      "type": "Number",
      "required": true
    },
    "newRates.patientRate": {
      "type": "Number",
      "required": true
    },
    "newRates.corporateRate": {
      "type": "Number",
      "required": true
    },
    "newRates.doctorRate": {
      "type": "Number",
      "required": true
    },
    "newRates.emergencyRate": {
      "type": "Number",
      "required": true
    },
    "newRates.referralRate": {
      "type": "Number"
    },
    "reason": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "changedBy.userId": {
      "type": "ObjectId",
      "required": true
    },
    "changedBy.name": {
      "type": "String",
      "required": true
    }
  },
  "refundPolicy": {
    "singleton": {
      "type": "String",
      "default": {
        "value": "refund-policy"
      }
    },
    "enabled": {
      "type": "Boolean",
      "default": {
        "value": true
      }
    },
    "stages": {
      "type": "Embedded",
      "default": {
        "value": {
          "beforeCollection": {
            "allowed": true,
            "refundPercent": 100
          },
          "afterCollection": {
            "allowed": true,
            "refundPercent": 50
          },
          "afterProcessing": {
            "allowed": true,
            "refundPercent": 25
          },
          "afterReport": {
            "allowed": false,
            "refundPercent": 0
          }
        }
      },
      "sub": {
        "beforeCollection": {
          "type": "Embedded",
          "default": {
            "value": {}
          },
          "sub": {
            "allowed": {
              "type": "Boolean",
              "default": {
                "value": true
              }
            },
            "refundPercent": {
              "type": "Number",
              "default": {
                "value": 0
              },
              "min": [
                0
              ],
              "max": [
                100
              ]
            }
          }
        },
        "afterCollection": {
          "type": "Embedded",
          "default": {
            "value": {}
          },
          "sub": {
            "allowed": {
              "type": "Boolean",
              "default": {
                "value": true
              }
            },
            "refundPercent": {
              "type": "Number",
              "default": {
                "value": 0
              },
              "min": [
                0
              ],
              "max": [
                100
              ]
            }
          }
        },
        "afterProcessing": {
          "type": "Embedded",
          "default": {
            "value": {}
          },
          "sub": {
            "allowed": {
              "type": "Boolean",
              "default": {
                "value": true
              }
            },
            "refundPercent": {
              "type": "Number",
              "default": {
                "value": 0
              },
              "min": [
                0
              ],
              "max": [
                100
              ]
            }
          }
        },
        "afterReport": {
          "type": "Embedded",
          "default": {
            "value": {}
          },
          "sub": {
            "allowed": {
              "type": "Boolean",
              "default": {
                "value": true
              }
            },
            "refundPercent": {
              "type": "Number",
              "default": {
                "value": 0
              },
              "min": [
                0
              ],
              "max": [
                100
              ]
            }
          }
        }
      }
    },
    "cancellationFee": {
      "type": "Number",
      "default": {
        "value": 0
      },
      "min": [
        0
      ]
    },
    "refundWindowDays": {
      "type": "Number",
      "default": {
        "value": 30
      },
      "min": [
        0
      ]
    },
    "fullRefundOnLabRejection": {
      "type": "Boolean",
      "default": {
        "value": true
      }
    },
    "allowAdminOverride": {
      "type": "Boolean",
      "default": {
        "value": true
      }
    },
    "policyNote": {
      "type": "String",
      "default": {
        "value": "Tests cancelled before the sample is drawn are refunded in full. Once a sample has been collected or processed, the consumables and bench time already spent are retained as per the rates above. A test whose report has been released cannot be refunded."
      },
      "trim": true
    },
    "updatedBy.userId": {
      "type": "String"
    },
    "updatedBy.name": {
      "type": "String"
    },
    "updatedBy.role": {
      "type": "String"
    },
    "updatedBy.at": {
      "type": "Date"
    }
  },
  "patient": {
    "uhid": {
      "type": "String",
      "required": true
    },
    "patientName": {
      "type": "String",
      "required": "Patient name is required",
      "trim": true
    },
    "gender": {
      "type": "String",
      "required": "Gender is required",
      "enum": {
        "values": [
          "Male",
          "Female",
          "Male Child",
          "Female Child",
          "Other",
          "Child"
        ]
      }
    },
    "dateOfBirth": {
      "type": "Date"
    },
    "age": {
      "type": "Number",
      "required": "Age is required",
      "min": [
        0
      ]
    },
    "mobile": {
      "type": "String",
      "required": "Mobile number is required",
      "trim": true
    },
    "address": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "city": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "state": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "pinCode": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "emergencyContact": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "referringDoctor": {
      "type": "ObjectId"
    },
    "organization": {
      "type": "ObjectId"
    },
    "registrationDate": {
      "type": "Date",
      "default": {
        "now": true
      }
    },
    "status": {
      "type": "String",
      "required": "Status is required",
      "default": {
        "value": "Active"
      },
      "enum": {
        "values": [
          "Active",
          "Inactive"
        ]
      }
    }
  },
  "appointment": {
    "appointmentId": {
      "type": "String",
      "required": true
    },
    "patient": {
      "type": "ObjectId"
    },
    "patientName": {
      "type": "String",
      "required": true,
      "trim": true
    },
    "mobile": {
      "type": "String",
      "required": true,
      "trim": true
    },
    "doctor": {
      "type": "ObjectId"
    },
    "tests": {
      "type": "Array",
      "item": "ObjectId"
    },
    "date": {
      "type": "Date",
      "required": true
    },
    "time": {
      "type": "String",
      "required": true
    },
    "collectionType": {
      "type": "String",
      "default": {
        "value": "Lab Visit"
      },
      "enum": {
        "values": [
          "Lab Visit",
          "Home Collection"
        ]
      }
    },
    "address": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "phlebotomist.userId": {
      "type": "String"
    },
    "phlebotomist.name": {
      "type": "String"
    },
    "phlebotomist.mobile": {
      "type": "String"
    },
    "status": {
      "type": "String",
      "default": {
        "value": "Pending"
      },
      "enum": {
        "values": [
          "Pending",
          "Confirmed",
          "Assigned",
          "On The Way",
          "Collected",
          "Submitted",
          "Completed",
          "Cancelled"
        ]
      }
    },
    "notes": {
      "type": "String",
      "default": {
        "value": ""
      }
    }
  },
  "invoice": {
    "invoiceNumber": {
      "type": "String",
      "required": true
    },
    "enquiryNo": {
      "type": "String"
    },
    "patient": {
      "type": "ObjectId",
      "required": true
    },
    "uhid": {
      "type": "String",
      "required": true
    },
    "referringDoctor": {
      "type": "ObjectId"
    },
    "referringDoctorName": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "organization": {
      "type": "ObjectId"
    },
    "chiefComplaint": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "clinicalNotes": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "priority": {
      "type": "String",
      "default": {
        "value": "Routine"
      },
      "enum": {
        "values": [
          "Routine",
          "Urgent"
        ]
      }
    },
    "items": {
      "type": "Array",
      "of": {
        "test": {
          "type": "ObjectId",
          "required": true
        },
        "testCode": {
          "type": "String",
          "required": true
        },
        "testName": {
          "type": "String",
          "required": true
        },
        "department": {
          "type": "ObjectId",
          "required": true
        },
        "departmentName": {
          "type": "String",
          "required": true
        },
        "rate": {
          "type": "Number",
          "required": true,
          "min": [
            0
          ]
        },
        "lineDiscountAmount": {
          "type": "Number",
          "default": {
            "value": 0
          },
          "min": [
            0
          ]
        },
        "discountAmount": {
          "type": "Number",
          "default": {
            "value": 0
          },
          "min": [
            0
          ]
        },
        "netAmount": {
          "type": "Number",
          "required": true,
          "min": [
            0
          ]
        },
        "processingMode": {
          "type": "String",
          "default": {
            "value": "In-house"
          },
          "enum": {
            "values": [
              "In-house",
              "Outsource"
            ]
          }
        },
        "outsourceLab": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "referralRate": {
          "type": "Number",
          "default": {
            "value": 0
          },
          "min": [
            0
          ]
        },
        "packageId": {
          "type": "ObjectId"
        },
        "packageName": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "cancelled": {
          "type": "Boolean",
          "default": {
            "value": false
          }
        },
        "cancelledAt": {
          "type": "Date"
        },
        "cancellationReason": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "refundedAmount": {
          "type": "Number",
          "default": {
            "value": 0
          },
          "min": [
            0
          ]
        },
        "retainedAmount": {
          "type": "Number",
          "default": {
            "value": 0
          },
          "min": [
            0
          ]
        },
        "cancelledBy.userId": {
          "type": "String"
        },
        "cancelledBy.name": {
          "type": "String"
        },
        "cancelledBy.role": {
          "type": "String"
        }
      }
    },
    "subtotal": {
      "type": "Number",
      "required": true,
      "min": [
        0
      ]
    },
    "discountType": {
      "type": "String",
      "default": {
        "value": "Fixed"
      },
      "enum": {
        "values": [
          "Percentage",
          "Fixed"
        ]
      }
    },
    "discountValue": {
      "type": "Number",
      "default": {
        "value": 0
      },
      "min": [
        0
      ]
    },
    "discountReason": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "discountDoctor": {
      "type": "ObjectId"
    },
    "discountDoctorName": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "netAmount": {
      "type": "Number",
      "required": true,
      "min": [
        0
      ]
    },
    "referralTotal": {
      "type": "Number",
      "default": {
        "value": 0
      },
      "min": [
        0
      ]
    },
    "paidAmount": {
      "type": "Number",
      "default": {
        "value": 0
      },
      "min": [
        0
      ]
    },
    "dueAmount": {
      "type": "Number",
      "default": {
        "value": 0
      },
      "min": [
        0
      ]
    },
    "paymentStatus": {
      "type": "String",
      "default": {
        "value": "Unpaid"
      },
      "enum": {
        "values": [
          "Paid",
          "Partial",
          "Unpaid",
          "Credit"
        ]
      }
    },
    "paymentMethod": {
      "type": "String",
      "default": {
        "value": "Cash"
      },
      "enum": {
        "values": [
          "Cash",
          "UPI",
          "Card",
          "Bank Transfer",
          "Cheque",
          "Online",
          "Credit"
        ]
      }
    },
    "paymentBreakdown": {
      "type": "Array",
      "default": {
        "value": []
      },
      "of": {
        "method": {
          "type": "String",
          "required": true,
          "enum": {
            "values": [
              "Cash",
              "UPI",
              "Card",
              "Bank Transfer",
              "Cheque",
              "Online",
              "Credit"
            ]
          }
        },
        "amount": {
          "type": "Number",
          "required": true,
          "min": [
            0
          ]
        }
      }
    },
    "barcode": {
      "type": "String",
      "required": true
    },
    "createdBy.userId": {
      "type": "ObjectId",
      "required": true
    },
    "createdBy.name": {
      "type": "String",
      "required": true
    },
    "revisions": {
      "type": "Array",
      "default": {
        "value": []
      },
      "of": {
        "at": {
          "type": "Date",
          "default": {
            "now": true
          }
        },
        "by.userId": {
          "type": "String"
        },
        "by.name": {
          "type": "String"
        },
        "by.role": {
          "type": "String"
        },
        "summary": {
          "type": "String",
          "default": {
            "value": ""
          },
          "trim": true
        },
        "testsAdded": {
          "type": "Array",
          "item": "String"
        },
        "netBefore": {
          "type": "Number",
          "default": {
            "value": 0
          }
        },
        "netAfter": {
          "type": "Number",
          "default": {
            "value": 0
          }
        }
      }
    }
  },
  "payment": {
    "receiptNumber": {
      "type": "String",
      "required": true
    },
    "invoice": {
      "type": "ObjectId",
      "required": true
    },
    "patient": {
      "type": "ObjectId",
      "required": true
    },
    "amount": {
      "type": "Number",
      "required": true,
      "min": [
        0
      ]
    },
    "paymentMethod": {
      "type": "String",
      "required": true,
      "enum": {
        "values": [
          "Cash",
          "UPI",
          "Card",
          "Bank Transfer",
          "Cheque",
          "Online",
          "Credit"
        ]
      }
    },
    "transactionRef": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "notes": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "receivedBy.userId": {
      "type": "ObjectId",
      "required": true
    },
    "receivedBy.name": {
      "type": "String",
      "required": true
    }
  },
  "paymentTransaction": {
    "txnId": {
      "type": "String",
      "required": true
    },
    "invoice": {
      "type": "ObjectId",
      "required": true
    },
    "patient": {
      "type": "ObjectId",
      "required": true
    },
    "amount": {
      "type": "Number",
      "required": true,
      "min": [
        1
      ]
    },
    "method": {
      "type": "String",
      "required": true,
      "enum": {
        "values": [
          "UPI",
          "Card"
        ]
      }
    },
    "status": {
      "type": "String",
      "default": {
        "value": "Pending"
      },
      "enum": {
        "values": [
          "Pending",
          "Success",
          "Failed",
          "Expired",
          "Cancelled"
        ]
      }
    },
    "vpa": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "upiIntent": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "utr": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "cardLast4": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "cardNetwork": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "authCode": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "rrn": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "payerToken": {
      "type": "String",
      "required": true
    },
    "failureReason": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "expiresAt": {
      "type": "Date",
      "required": true
    },
    "completedAt": {
      "type": "Date"
    },
    "payment": {
      "type": "ObjectId"
    },
    "initiatedBy.userId": {
      "type": "ObjectId",
      "required": true
    },
    "initiatedBy.name": {
      "type": "String",
      "required": true
    }
  },
  "refund": {
    "refundId": {
      "type": "String",
      "required": true
    },
    "invoice": {
      "type": "ObjectId",
      "required": true
    },
    "patient": {
      "type": "ObjectId",
      "required": true
    },
    "originalAmount": {
      "type": "Number",
      "required": true
    },
    "refundAmount": {
      "type": "Number",
      "required": true
    },
    "reason": {
      "type": "String",
      "required": true
    },
    "paymentMethod": {
      "type": "String",
      "required": true,
      "enum": {
        "values": [
          "Cash",
          "UPI",
          "Card",
          "Bank Transfer",
          "Cheque",
          "Online"
        ]
      }
    },
    "approvedBy.userId": {
      "type": "String",
      "required": true
    },
    "approvedBy.name": {
      "type": "String",
      "required": true
    },
    "approvedBy.role": {
      "type": "String",
      "required": true
    },
    "date": {
      "type": "Date",
      "default": {
        "now": true
      }
    },
    "remarks": {
      "type": "String",
      "default": {
        "value": ""
      }
    }
  },
  "expense": {
    "expenseId": {
      "type": "String",
      "required": true
    },
    "payeeType": {
      "type": "String",
      "default": {
        "value": "Other"
      },
      "enum": {
        "values": [
          "Ambulance",
          "Doctor Referral",
          "Collection Agent",
          "Courier",
          "Staff Advance",
          "Vendor / Supplier",
          "Reagents & Consumables",
          "Equipment & Maintenance",
          "Rent & Utilities",
          "Other"
        ]
      }
    },
    "payeeName": {
      "type": "String",
      "required": "Who the money is paid to is required",
      "trim": true
    },
    "payeeContact": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "category": {
      "type": "String",
      "required": true
    },
    "description": {
      "type": "String",
      "required": true
    },
    "amount": {
      "type": "Number",
      "required": true,
      "min": [
        1,
        "Payout amount must be greater than zero"
      ]
    },
    "paymentMethod": {
      "type": "String",
      "default": {
        "value": "Cash"
      },
      "enum": {
        "values": [
          "Cash",
          "UPI",
          "Card",
          "Bank Transfer",
          "Cheque",
          "Online"
        ]
      }
    },
    "referenceNo": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "expenseDate": {
      "type": "Date",
      "default": {
        "now": true
      }
    },
    "status": {
      "type": "String",
      "default": {
        "value": "Paid"
      },
      "enum": {
        "values": [
          "Pending",
          "Paid",
          "Rejected"
        ]
      }
    },
    "needsApproval": {
      "type": "Boolean",
      "default": {
        "value": false
      }
    },
    "patient": {
      "type": "ObjectId"
    },
    "invoice": {
      "type": "ObjectId"
    },
    "doctor": {
      "type": "ObjectId"
    },
    "recordedBy.userId": {
      "type": "String",
      "required": true
    },
    "recordedBy.name": {
      "type": "String",
      "required": true
    },
    "recordedBy.role": {
      "type": "String"
    },
    "approvedBy.userId": {
      "type": "String"
    },
    "approvedBy.name": {
      "type": "String"
    },
    "approvedBy.role": {
      "type": "String"
    },
    "approvedBy.at": {
      "type": "Date"
    },
    "rejectionReason": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "receiptUrl": {
      "type": "String",
      "default": {
        "value": ""
      }
    }
  },
  "sample": {
    "sampleId": {
      "type": "String",
      "required": true
    },
    "barcode": {
      "type": "String",
      "required": true
    },
    "patient": {
      "type": "ObjectId",
      "required": true
    },
    "uhid": {
      "type": "String",
      "required": true
    },
    "enquiryNo": {
      "type": "String"
    },
    "invoice": {
      "type": "ObjectId",
      "required": true
    },
    "test": {
      "type": "ObjectId",
      "required": true
    },
    "testCode": {
      "type": "String",
      "required": true
    },
    "testName": {
      "type": "String",
      "required": true
    },
    "department": {
      "type": "ObjectId",
      "required": true
    },
    "sampleType": {
      "type": "String",
      "required": true
    },
    "sampleContainer": {
      "type": "String",
      "required": true
    },
    "processingMode": {
      "type": "String",
      "default": {
        "value": "In-house"
      },
      "enum": {
        "values": [
          "In-house",
          "Outsource"
        ]
      }
    },
    "outsourceLab": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "collectionDate": {
      "type": "Date"
    },
    "collectionTime": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "collector": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "status": {
      "type": "String",
      "default": {
        "value": "Pending Collection"
      },
      "enum": {
        "values": [
          "Registered",
          "Pending Collection",
          "Collected",
          "Received",
          "Processing",
          "Completed",
          "Rejected",
          "Recollected",
          "Cancelled"
        ]
      }
    },
    "priority": {
      "type": "String",
      "default": {
        "value": "Routine"
      },
      "enum": {
        "values": [
          "Routine",
          "Urgent"
        ]
      }
    },
    "chiefComplaint": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "rejectionReason": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "rejectionRemarks": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "rejectedBy.userId": {
      "type": "ObjectId"
    },
    "rejectedBy.name": {
      "type": "String"
    },
    "rejectedAt": {
      "type": "Date"
    },
    "cancelledAt": {
      "type": "Date"
    },
    "cancellationReason": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "receivedAt": {
      "type": "Date"
    },
    "processingAt": {
      "type": "Date"
    },
    "completedAt": {
      "type": "Date"
    },
    "expectedAt": {
      "type": "Date"
    },
    "recollectionCount": {
      "type": "Number",
      "default": {
        "value": 0
      }
    },
    "statusHistory": {
      "type": "Array",
      "of": {
        "fromStatus": {
          "type": "String"
        },
        "toStatus": {
          "type": "String",
          "required": true
        },
        "updatedBy.userId": {
          "type": "ObjectId",
          "required": true
        },
        "updatedBy.name": {
          "type": "String",
          "required": true
        },
        "updatedBy.role": {
          "type": "String",
          "required": true
        },
        "timestamp": {
          "type": "Date",
          "default": {
            "now": true
          }
        },
        "notes": {
          "type": "String",
          "default": {
            "value": ""
          }
        }
      }
    }
  },
  "result": {
    "resultId": {
      "type": "String",
      "required": true
    },
    "patient": {
      "type": "ObjectId",
      "required": true
    },
    "uhid": {
      "type": "String",
      "required": true
    },
    "enquiryNo": {
      "type": "String"
    },
    "invoice": {
      "type": "ObjectId",
      "required": true
    },
    "sample": {
      "type": "ObjectId",
      "required": true
    },
    "test": {
      "type": "ObjectId",
      "required": true
    },
    "department": {
      "type": "ObjectId",
      "required": true
    },
    "results": {
      "type": "Array",
      "of": {
        "parameterId": {
          "type": "String"
        },
        "parameterName": {
          "type": "String",
          "required": true
        },
        "shortName": {
          "type": "String"
        },
        "value": {
          "type": "String",
          "default": {
            "value": ""
          }
        },
        "unit": {
          "type": "String",
          "default": {
            "value": ""
          }
        },
        "referenceRange": {
          "type": "String",
          "default": {
            "value": ""
          }
        },
        "flag": {
          "type": "String",
          "default": {
            "value": "Normal"
          },
          "enum": {
            "values": [
              "Normal",
              "Low",
              "High",
              "Critical"
            ]
          }
        },
        "flagManual": {
          "type": "Boolean",
          "default": {
            "value": false
          }
        },
        "method": {
          "type": "String",
          "default": {
            "value": ""
          }
        },
        "remarks": {
          "type": "String",
          "default": {
            "value": ""
          }
        },
        "resultType": {
          "type": "String",
          "default": {
            "value": "Numeric"
          }
        },
        "dropdownOptions": {
          "type": "Array",
          "item": "String"
        },
        "criticalLow": {
          "type": "String",
          "default": {
            "value": ""
          }
        },
        "criticalHigh": {
          "type": "String",
          "default": {
            "value": ""
          }
        },
        "highRange": {
          "type": "String",
          "default": {
            "value": ""
          }
        },
        "lowRange": {
          "type": "String",
          "default": {
            "value": ""
          }
        },
        "displayOrder": {
          "type": "Number",
          "default": {
            "value": 1
          }
        },
        "formula": {
          "type": "String",
          "default": {
            "value": ""
          }
        },
        "formulaOverride": {
          "type": "Boolean",
          "default": {
            "value": false
          }
        }
      }
    },
    "status": {
      "type": "String",
      "default": {
        "value": "Draft"
      },
      "enum": {
        "values": [
          "Draft",
          "Submitted",
          "Under Review",
          "Approved",
          "Rejected",
          "Final"
        ]
      }
    },
    "overallRemarks": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "enteredBy.userId": {
      "type": "String",
      "required": true
    },
    "enteredBy.name": {
      "type": "String",
      "required": true
    },
    "enteredBy.role": {
      "type": "String",
      "required": true
    },
    "enteredBy.date": {
      "type": "Date",
      "default": {
        "now": true
      }
    },
    "verifiedBy.userId": {
      "type": "String"
    },
    "verifiedBy.name": {
      "type": "String"
    },
    "verifiedBy.role": {
      "type": "String"
    },
    "verifiedBy.date": {
      "type": "Date"
    },
    "rejectionReason": {
      "type": "String",
      "default": {
        "value": ""
      }
    },
    "versions": {
      "type": "Array",
      "of": {
        "version": {
          "type": "Number",
          "required": true
        },
        "changedBy.userId": {
          "type": "String",
          "required": true
        },
        "changedBy.name": {
          "type": "String",
          "required": true
        },
        "changedBy.role": {
          "type": "String",
          "required": true
        },
        "results": {
          "type": "Array",
          "of": {
            "parameterId": {
              "type": "String"
            },
            "parameterName": {
              "type": "String",
              "required": true
            },
            "shortName": {
              "type": "String"
            },
            "value": {
              "type": "String",
              "default": {
                "value": ""
              }
            },
            "unit": {
              "type": "String",
              "default": {
                "value": ""
              }
            },
            "referenceRange": {
              "type": "String",
              "default": {
                "value": ""
              }
            },
            "flag": {
              "type": "String",
              "default": {
                "value": "Normal"
              },
              "enum": {
                "values": [
                  "Normal",
                  "Low",
                  "High",
                  "Critical"
                ]
              }
            },
            "flagManual": {
              "type": "Boolean",
              "default": {
                "value": false
              }
            },
            "method": {
              "type": "String",
              "default": {
                "value": ""
              }
            },
            "remarks": {
              "type": "String",
              "default": {
                "value": ""
              }
            },
            "resultType": {
              "type": "String",
              "default": {
                "value": "Numeric"
              }
            },
            "dropdownOptions": {
              "type": "Array",
              "item": "String"
            },
            "criticalLow": {
              "type": "String",
              "default": {
                "value": ""
              }
            },
            "criticalHigh": {
              "type": "String",
              "default": {
                "value": ""
              }
            },
            "highRange": {
              "type": "String",
              "default": {
                "value": ""
              }
            },
            "lowRange": {
              "type": "String",
              "default": {
                "value": ""
              }
            },
            "displayOrder": {
              "type": "Number",
              "default": {
                "value": 1
              }
            },
            "formula": {
              "type": "String",
              "default": {
                "value": ""
              }
            },
            "formulaOverride": {
              "type": "Boolean",
              "default": {
                "value": false
              }
            }
          }
        },
        "status": {
          "type": "String",
          "required": true
        },
        "reason": {
          "type": "String",
          "default": {
            "value": ""
          }
        },
        "timestamp": {
          "type": "Date",
          "default": {
            "now": true
          }
        }
      }
    }
  },
  "savedReport": {
    "result": {
      "type": "ObjectId",
      "required": true
    },
    "patient": {
      "type": "ObjectId"
    },
    "patientName": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "uhid": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "mobile": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "invoice": {
      "type": "ObjectId"
    },
    "invoiceNumber": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "enquiryNo": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "reportNo": {
      "type": "String",
      "default": {
        "value": ""
      },
      "trim": true
    },
    "status": {
      "type": "String",
      "default": {
        "value": "Final"
      },
      "enum": {
        "values": [
          "Provisional",
          "Final"
        ]
      }
    },
    "tests": {
      "type": "Array",
      "default": {
        "value": []
      },
      "item": "String"
    },
    "fileName": {
      "type": "String",
      "required": true
    },
    "size": {
      "type": "Number",
      "default": {
        "value": 0
      }
    },
    "data": {
      "type": "Buffer",
      "required": true
    },
    "savedBy.userId": {
      "type": "String"
    },
    "savedBy.name": {
      "type": "String"
    },
    "savedBy.role": {
      "type": "String"
    }
  }
};
